### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by hawkingswheelchair** [Flying-Toast/memrise-cheat#1]
I receive the error message:
 
Failed to load resource: net::ERR_FAILED
review:1 Access to font at 'https://static.memrise.com/webclient/_next/static/fonts/73499f2fb5eb9691e8f8a1d92ec83f9b.woff' from origin 'https://app.memrise.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Am I doing something wrong or was something changed with the website (CORS policy on headers)? Is there a way around this?

**Comment by Flying-Toast** [comment]
Sorry, I don't use this anymore (and to be honest it's not written in a very stable way either). Feel free to look through the code and try to troubleshoot it, but I don't have the time or reason to do it myself.

Thanks
