### ISSUE TITLE
it is not working

### ISSUE THREAD

**Issue by Shaaken** [Flying-Toast/memrise-cheat#3]
when i click prepare it has no effect. am I doing something wrong? I imported it as a google chrome extension as the information implied and it does not work for me at the moment

**Comment by Snowpop** [comment]
Lol I have the same maybe the creator should make an how to use README file

**Comment by Flying-Toast** [comment]
I've long finished the French class I made this for. If you want to use it, feel free to try and fix it for the latest memrise version, but I'm not gonna work on your homework for you.
